### ISSUE TITLE
interaction: Incorrectly checking for a valid guild 

### ISSUE THREAD

**Issue by saucesteals** [AndreasHGK/go-interactions#1]
https://github.com/AndreasHGK/go-interactions/blob/2600d1cdb7fe709d6fb90a300f5103771b650ea1/cmd/interaction.go#L129

(Assuming this was intended to be used as DM/Guild differentiation)

Arikawa internally differentiates DMs and Guilds with the `isValid()` method on the `Snowflake` 
GuildIDs from DMs are set as `GuildId(0)` even tho `NullSnowflake` exists (which is the exact opposite: `^GuildId(0)`)
Example: 
https://github.com/diamondburned/arikawa/blob/16a408bf3024bb4baa2a8c06fb84a65f0b5736af/state/state.go#L186

**Comment by sunny17347** [comment]
this fucking sucks

**Comment by andreashgk** [comment]
Thank you, I was not aware of this. Should be patched in the latest commit!
